import { Bay } from "../model";
const MAX_NUMBER = 999999;
export default<Bay> {
    bayId:'LY',
    dimension:{
        width:260000,
        height:36000
    },
    cranes: [
        {
            id: '31',
            label: '31',
            y: 3000,
            z: MAX_NUMBER,
            left: 50000,
            top: 1640,
            width: 2800,
            height: 36000,
            trolleyHeight: 1000, // 小车在缩略图上的高度, 固定值
            status: MAX_NUMBER,
            occupied: false,
            wmsMode: 999999,
            activityStatus: 0,
            rotateAngleAct: 0,
            pawActWidth: 0,
            gantryTelemeter: 0,
            trolleyTelemeter: 0,
            rejectionReason: 0,
            faultCode: 0,
            tagProps: [
              ['left', '31_GlobalStatusXPosition'],
              ['y', '31_GlobalStatusYPosition'],
              ['z', '31_GlobalStatusZPosition'],
              ['s', '31_CltsTrackButton'],
              ['orderLock', '31_HMI_A6_ORDER_LOCK'],
              ['xMax', '31_xMax'],
              ['occupied', '31_GlobalStatusCraneLoaded'],
              ['wmsMode', '31_HMI_A6_WMS_MODE'],
              ['activityStatus', '31_ActivityStatus'],
              ['rotateAngleAct', '31_GlobalStatusTongRotationAngle'],
              ['pawActWidth', '31_GlobalStatusTongOpennessWidth'],
              ['gantryTelemeter', '31_GlobalStatusGantryTelemeterStatus'],
              ['trolleyTelemeter', '31_GlobalStatusTrolleyTelemeterStatus'],
              ['rejectionReason', '31_ActivityResponseRejectionReason'],
              ['faultCode', '31_GlobalStatusFaultCode'],
            ],
          },
          {
            id: '32',
            label: '32',
            y: 4000,
            z: MAX_NUMBER,
            left: 100000,
            top: 1640,
            width: 2800,
            height: 36000,
            trolleyHeight: 1000,
            status: MAX_NUMBER,
            occupied: false,
            wmsMode: 999999,
            activityStatus: 0,
            rotateAngleAct: 0,
            pawActWidth: 0,
            gantryTelemeter: 0,
            trolleyTelemeter: 0,
            rejectionReason: 0,
            faultCode: 0,
            tagProps: [
              ['left', '32_GlobalStatusXPosition'],
              ['y', '32_GlobalStatusYPosition'],
              ['z', '32_GlobalStatusZPosition'],
              ['s', '32_CltsTrackButton'],
              ['orderLock', '32_HMI_A6_ORDER_LOCK'],
              ['xMax', '32_xMax'],
              ['occupied', '32_GlobalStatusCraneLoaded'],
              ['wmsMode', '32_HMI_A6_WMS_MODE'],
              ['activityStatus', '32_ActivityStatus'],
              ['rotateAngleAct', '32_GlobalStatusTongRotationAngle'],
              ['pawActWidth', '32_GlobalStatusTongOpennessWidth'],
              ['gantryTelemeter', '32_GlobalStatusGantryTelemeterStatus'],
              ['trolleyTelemeter', '32_GlobalStatusTrolleyTelemeterStatus'],
              ['rejectionReason', '32_ActivityResponseRejectionReason'],
              ['faultCode', '32_GlobalStatusFaultCode'],
            ],
          },
          {
            id: '33',
            label: '33',
            y: 5000,
            z: MAX_NUMBER,
            left: 250000,
            top: 1640,
            width: 2800,
            height: 36000,
            trolleyHeight: 1000,
            status: MAX_NUMBER,
            occupied: false,
            wmsMode: 999999,
            activityStatus: 0,
            rotateAngleAct: 0,
            pawActWidth: 0,
            gantryTelemeter: 0,
            trolleyTelemeter: 0,
            rejectionReason: 0,
            faultCode: 0,
            tagProps: [
              ['left', '33_GlobalStatusXPosition'],
              ['y', '33_GlobalStatusYPosition'],
              ['z', '33_GlobalStatusZPosition'],
              ['s', '33_CltsTrackButton'],
              ['orderLock', '33_HMI_A6_ORDER_LOCK'],
              ['xMax', '33_xMax'],
              ['occupied', '33_GlobalStatusCraneLoaded'],
              ['wmsMode', '33_HMI_A6_WMS_MODE'],
              ['activityStatus', '33_ActivityStatus'],
              ['rotateAngleAct', '33_GlobalStatusTongRotationAngle'],
              ['pawActWidth', '33_GlobalStatusTongOpennessWidth'],
              ['gantryTelemeter', '33_GlobalStatusGantryTelemeterStatus'],
              ['trolleyTelemeter', '33_GlobalStatusTrolleyTelemeterStatus'],
              ['rejectionReason', '33_ActivityResponseRejectionReason'],
              ['faultCode', '33_GlobalStatusFaultCode'],
            ],
          },
    ],
    parkings: [
        {
            id: 'LTR01',
            label: 'LTR01',
            left: 177433,
            top: 24792,
            width: 15151,
            height: 4623,
            horizontal: true,
            locked: false,
          },
          {
            id: 'LTR02',
            label: 'LTR02',
            left: 202844,
            top: 24792,
            width: 15151,
            height: 4623,
            horizontal: true,
            locked: false,
          },
      ],
    safetyZones: [
        { id: 'LY1', label: 'LY1', left: 17700, top: 5420, width: 33070, height: 9680, lockStatus: -1 },
        { id: 'LY2', label: 'LY2', left: 54160, top: 5420, width: 17110, height: 9680, lockStatus: -1 },
        { id: 'LY3', label: 'LY3', left: 81060, top: 5420, width: 26150, height: 9680, lockStatus: -1 },
    
        { id: 'LY5', label: 'LY5', left: 161210, top: 5420, width: 12600, height: 9680, lockStatus: -1 },
        { id: 'LY6', label: 'LY6', left: 177180, top: 5420, width: 28600, height: 9680, lockStatus: -1 },
        { id: 'LY7', label: 'LY7', left: 209030, top: 5420, width: 7900, height: 9680, lockStatus: -1 },
        {
          id: 'PIT',
          label: '保温坑',
          left: 8480,
          top: 24650,
          width: 14800,
          height: 9610,
          lockStatus: -1,
          baseStyle: 'border-right: none',
        },
        { id: 'LYA', label: 'LYA', left: 23280, top: 24650, width: 19120, height: 9610, lockStatus: -1 },
        { id: 'LYB', label: 'LYB', left: 54260, top: 24650, width: 28840, height: 9610, lockStatus: -1 },
        { id: 'LYC', label: 'LYC', left: 86260, top: 24650, width: 28600, height: 9610, lockStatus: -1 },
        { id: 'LYD', label: 'LYD', left: 118280, top: 24650, width: 28600, height: 9610, lockStatus: -1 },
        { id: 'LYE', label: 'LYE', left: 150220, top: 24650, width: 7960, height: 9610, lockStatus: -1 },
    ]
}