import { Bay } from "../model";
const MAX_NUMBER = 999999;
export default<Bay> {
    bayId: 'PY',
    dimension: { width: 260000, height: 33000 },
    cranes: [
        {
            id: '51',
            label: '51',
            y: 0,
            z: MAX_NUMBER,
            left: 50000,
            top: 1640,
            width: 2800,
            height: 33000,
            trolleyHeight: 1000,
            status: MAX_NUMBER,
            occupied: false,
            wmsMode: 999999,
            activityStatus: 0,
            rotateAngleAct: 0,
            pawActWidth: 0,
            gantryTelemeter: 0,
            trolleyTelemeter: 0,
            rejectionReason: 0,
            faultCode: 0,
            tagProps: [
              ['left', '51_GlobalStatusXPosition'],
              ['y', '51_GlobalStatusYPosition'],
              ['z', '51_GlobalStatusZPosition'],
              ['s', '51_CltsTrackButton'],
              ['orderLock', '51_HMI_A6_ORDER_LOCK'],
              ['xMax', '51_xMax'],
              ['occupied', '51_GlobalStatusCraneLoaded'],
              ['wmsMode', '51_GlobalStatusRunningMode'],
              ['activityStatus', '51_ActivityStatus'],
              ['rotateAngleAct', '51_GlobalStatusTongRotationAngle'],
              ['pawActWidth', '51_GlobalStatusTongOpennessWidth'],
              ['gantryTelemeter', '51_GlobalStatusGantryTelemeterStatus'],
              ['trolleyTelemeter', '51_GlobalStatusTrolleyTelemeterStatus'],
              ['rejectionReason', '51_ActivityResponseRejectionReason'],
              ['faultCode', '51_GlobalStatusFaultCode'],
            ],
          },
          {
            id: '52',
            label: '52',
            y: 4000,
            z: MAX_NUMBER,
            left: 100000,
            top: 1640,
            width: 2800,
            height: 33000,
            trolleyHeight: 1000,
            status: MAX_NUMBER,
            occupied: false,
            wmsMode: 999999,
            activityStatus: 0,
            rotateAngleAct: 0,
            pawActWidth: 0,
            gantryTelemeter: 0,
            trolleyTelemeter: 0,
            rejectionReason: 0,
            faultCode: 0,
            tagProps: [
              ['left', '52_GlobalStatusXPosition'],
              ['y', '52_GlobalStatusYPosition'],
              ['z', '52_GlobalStatusZPosition'],
              ['s', '52_CltsTrackButton'],
              ['orderLock', '52_HMI_A6_ORDER_LOCK'],
              ['xMax', '52_xMax'],
              ['occupied', '52_GlobalStatusCraneLoaded'],
              ['wmsMode', '52_GlobalStatusRunningMode'],
              ['activityStatus', '52_ActivityStatus'],
              ['rotateAngleAct', '52_GlobalStatusTongRotationAngle'],
              ['pawActWidth', '52_GlobalStatusTongOpennessWidth'],
              ['gantryTelemeter', '52_GlobalStatusGantryTelemeterStatus'],
              ['trolleyTelemeter', '52_GlobalStatusTrolleyTelemeterStatus'],
              ['rejectionReason', '52_ActivityResponseRejectionReason'],
              ['faultCode', '52_GlobalStatusFaultCode'],
            ],
          },
          {
            id: '53',
            label: '53',
            y: 5000,
            z: MAX_NUMBER,
            left: 250000,
            top: 1640,
            width: 2800,
            height: 33000,
            trolleyHeight: 1000,
            status: MAX_NUMBER,
            occupied: false,
            wmsMode: 999999,
            activityStatus: 0,
            rotateAngleAct: 0,
            pawActWidth: 0,
            gantryTelemeter: 0,
            trolleyTelemeter: 0,
            rejectionReason: 0,
            faultCode: 0,
            tagProps: [
              ['left', '53_GlobalStatusXPosition'],
              ['y', '53_GlobalStatusYPosition'],
              ['z', '53_GlobalStatusZPosition'],
              ['s', '53_CltsTrackButton'],
              ['orderLock', '53_HMI_A6_ORDER_LOCK'],
              ['xMax', '53_xMax'],
              ['occupied', '53_GlobalStatusCraneLoaded'],
              ['wmsMode', '53_GlobalStatusRunningMode'],
              ['activityStatus', '53_ActivityStatus'],
              ['rotateAngleAct', '53_GlobalStatusTongRotationAngle'],
              ['pawActWidth', '53_GlobalStatusTongOpennessWidth'],
              ['gantryTelemeter', '53_GlobalStatusGantryTelemeterStatus'],
              ['trolleyTelemeter', '53_GlobalStatusTrolleyTelemeterStatus'],
              ['rejectionReason', '53_ActivityResponseRejectionReason'],
              ['faultCode', '53_GlobalStatusFaultCode'],
            ],
          },
    ],
    parkings: [
        {
            id: 'PTR01',
            label: 'PTR01',
            left: 179296,
            top: 23564,
            width: 15200,
            height: 4623,
            horizontal: true,
            locked: false,
          },
          {
            id: 'PTR02',
            label: 'PTR02',
            left: 204696,
            top: 23564,
            width: 15200,
            height: 4623,
            horizontal: true,
            locked: false,
          },
          {
            id: 'PTR03',
            label: 'P\nT\nR\n0\n3',
            left: 73329,
            top: 4452,
            width: 3808,
            height: 13115,
            horizontal: false,
            locked: false,
          },
      ],
    safetyZones: [
        { id: 'PY1', label: 'PY1', left: 7100, top: 4800, width: 21700, height: 19300, lockStatus: -1 },
        { id: 'PY2_A', label: 'PY2_A', left: 32100, top: 4800, width: 37830, height: 19300, lockStatus: -1 },
        { id: 'PY2_B', label: 'PY2_B', left: 50530, top: 24000, width: 19410, height: 7800, lockStatus: -1 },
        { id: 'PY4', label: 'PY4', left: 178750, top: 5040, width: 18510, height: 17630, lockStatus: -1 },
        { id: 'PY5', label: 'PY5', left: 198210, top: 5040, width: 17440, height: 17630, lockStatus: -1 },
        { id: 'PY6', label: 'PY6', left: 218820, top: 5040, width: 17580, height: 17630, lockStatus: -1 },
    ]
}