import { Bay } from "../model";
const MAX_NUMBER = 999999;
export default<Bay> {
    bayId: 'ZY',
    dimension: { width: 260000, height: 35000 },
    cranes: [
        {
          id: '41',
          label: '41',
          y: 3000,
          z: MAX_NUMBER,
          left: 50000,
          top: 1640,
          width: 2800,
          height: 33000,
          trolleyHeight: 1000,
          status: MAX_NUMBER,
          occupied: false,
          wmsMode: 999999,
          activityStatus: 0,
          rotateAngleAct: 0,
          pawActWidth: 0,
          gantryTelemeter: 0,
          trolleyTelemeter: 0,
          rejectionReason: 0,
          faultCode: 0,
          tagProps: [
            ['left', '41_GlobalStatusXPosition'],
            ['y', '41_GlobalStatusYPosition'],
            ['z', '41_GlobalStatusZPosition'],
            ['s', '41_CltsTrackButton'],
            ['orderLock', '41_HMI_A6_ORDER_LOCK'],
            ['xMax', '41_xMax'],
            ['occupied', '41_GlobalStatusCraneLoaded'],
            ['wmsMode', '41_HMI_A6_WMS_MODE'],
            ['activityStatus', '41_ActivityStatus'],
            ['rotateAngleAct', '41_GlobalStatusTongRotationAngle'],
            ['pawActWidth', '41_GlobalStatusTongOpennessWidth'],
            ['gantryTelemeter', '41_GlobalStatusGantryTelemeterStatus'],
            ['trolleyTelemeter', '41_GlobalStatusTrolleyTelemeterStatus'],
            ['rejectionReason', '41_ActivityResponseRejectionReason'],
            ['faultCode', '41_GlobalStatusFaultCode'],
          ],
        },
        {
          id: '42',
          label: '42',
          y: 4000,
          z: MAX_NUMBER,
          left: 100000,
          top: 1640,
          width: 2800,
          height: 33000,
          trolleyHeight: 1000,
          status: MAX_NUMBER,
          occupied: false,
          wmsMode: 999999,
          activityStatus: 0,
          rotateAngleAct: 0,
          pawActWidth: 0,
          gantryTelemeter: 0,
          trolleyTelemeter: 0,
          rejectionReason: 0,
          faultCode: 0,
          tagProps: [
            ['left', '42_GlobalStatusXPosition'],
            ['y', '42_GlobalStatusYPosition'],
            ['z', '42_GlobalStatusZPosition'],
            ['s', '42_CltsTrackButton'],
            ['orderLock', '42_HMI_A6_ORDER_LOCK'],
            ['xMax', '42_xMax'],
            ['occupied', '42_GlobalStatusCraneLoaded'],
            ['wmsMode', '42_HMI_A6_WMS_MODE'],
            ['activityStatus', '42_ActivityStatus'],
            ['rotateAngleAct', '42_GlobalStatusTongRotationAngle'],
            ['pawActWidth', '42_GlobalStatusTongOpennessWidth'],
            ['gantryTelemeter', '42_GlobalStatusGantryTelemeterStatus'],
            ['trolleyTelemeter', '42_GlobalStatusTrolleyTelemeterStatus'],
            ['rejectionReason', '42_ActivityResponseRejectionReason'],
            ['faultCode', '42_GlobalStatusFaultCode'],
          ],
        },
        {
          id: '43',
          label: '43',
          y: 5000,
          z: MAX_NUMBER,
          left: 250000,
          top: 1640,
          width: 2800,
          height: 33000,
          trolleyHeight: 1000,
          status: MAX_NUMBER,
          occupied: false,
          wmsMode: 999999,
          activityStatus: 0,
          rotateAngleAct: 0,
          pawActWidth: 0,
          gantryTelemeter: 0,
          trolleyTelemeter: 0,
          rejectionReason: 0,
          faultCode: 0,
          tagProps: [
            ['left', '43_GlobalStatusXPosition'],
            ['y', '43_GlobalStatusYPosition'],
            ['z', '43_GlobalStatusZPosition'],
            ['s', '43_CltsTrackButton'],
            ['orderLock', '43_HMI_A6_ORDER_LOCK'],
            ['xMax', '43_xMax'],
            ['occupied', '43_GlobalStatusCraneLoaded'],
            ['wmsMode', '43_HMI_A6_WMS_MODE'],
            ['activityStatus', '43_ActivityStatus'],
            ['rotateAngleAct', '43_GlobalStatusTongRotationAngle'],
            ['pawActWidth', '43_GlobalStatusTongOpennessWidth'],
            ['gantryTelemeter', '43_GlobalStatusGantryTelemeterStatus'],
            ['trolleyTelemeter', '43_GlobalStatusTrolleyTelemeterStatus'],
            ['rejectionReason', '43_ActivityResponseRejectionReason'],
            ['faultCode', '43_GlobalStatusFaultCode'],
          ],
        },
    ],
    parkings: [
        {
          id: 'ZTR01',
          label: 'ZTR01',
          left: 180088,
          top: 23781,
          width: 14943,
          height: 4456,
          horizontal: true,
          locked: false,
        },
        {
          id: 'ZTR02',
          label: 'ZTR02',
          left: 205114,
          top: 23781,
          width: 14943,
          height: 4456,
          horizontal: true,
          locked: true,
        },
      ],
    safetyZones: [
        { id: 'ZY11', label: 'ZY1_A', left: 18700, top: 14110, width: 33200, height: 10030, lockStatus: -1 },
    {
      id: 'ZY12',
      label: 'ZY1_B',
      left: 18700,
      top: 24140,
      width: 33200,
      height: 10030,
      lockStatus: -1,
      borderlessTop: true,
    },
    { id: 'ZY21', label: 'ZY2_A', left: 55230, top: 6370, width: 17100, height: 13900, lockStatus: -1 },
    {
      id: 'ZY22',
      label: 'ZY2_B',
      left: 55230,
      top: 20270,
      width: 17100,
      height: 13900,
      lockStatus: -1,
      borderlessTop: true,
    },
    { id: 'ZY31', label: 'ZY3_A', left: 82020, top: 5780, width: 28600, height: 13950, lockStatus: -1 },
    {
      id: 'ZY32',
      label: 'ZY3_B',
      left: 82020,
      top: 19730,
      width: 28600,
      height: 13950,
      lockStatus: -1,
      borderlessTop: true,
    },
    {
      id: 'ZY41',
      label: 'ZY4_A',
      left: 114000,
      top: 5780,
      width: 7900,
      height: 13950,
      lockStatus: -1,
      baseStyle: 'border-bottom: none !important;',
    },
    {
      id: 'ZY42',
      label: 'ZY4_B',
      left: 114000,
      top: 19730,
      width: 26300,
      height: 13950,
      lockStatus: -1,
    },
    { id: 'ZY6', label: 'ZY6', left: 183430, top: 5800, width: 26300, height: 17430, lockStatus: -1 },
    { id: 'ZY7', label: 'ZY7', left: 212970, top: 5600, width: 21880, height: 17630, lockStatus: -1 },
    ]
}